import { Platform, StyleSheet } from 'react-native';


export const darkTheme = {
  background: '#1d1b18',
  card: '#24211d',
  text: '#f4f0e8',
  muted: '#c7b8a5',
  border: '#655e55',
  placeholder: '#8b7b68',
  warning: '#a3264d',
  undoBackground: '#24211d',
  secondaryActionBackground: '#302b25',
  secondaryActionText: '#f4f0e8',
};

export const lightTheme = {
  background: '#f4f0e8',
  card: '#fbf8f2',
  text: '#1d1b18',
  muted: '#655e55',
  border: '#c7b8a5',
  placeholder: '#9b8770',
  warning: '#8a1538',
  undoBackground: '#fbf8f2',
  secondaryActionBackground: '#eadfce',
  secondaryActionText: '#1d1b18',
};

export type Theme = typeof darkTheme;

export const styles = StyleSheet.create({
  root: { flex: 1 },
  safe: { flex: 1 },
  header: { paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: { fontSize: 24, fontWeight: '900' },
  subtitle: { fontSize: 13, marginTop: 2 },
  primaryButton: { backgroundColor: '#8a1538', paddingHorizontal: 18, paddingVertical: 12, borderRadius: 14, minHeight: 46, justifyContent: 'center' },
  primaryButtonLarge: { backgroundColor: '#8a1538', paddingHorizontal: 18, paddingVertical: 14, borderRadius: 14, minHeight: 50, justifyContent: 'center', alignItems: 'center', marginTop: 16 },
  primaryButtonText: { color: '#ffffff', fontWeight: '900', fontSize: 16 },
  tabs: { flexDirection: 'row', padding: 8, borderBottomWidth: 1, gap: 8 },
  tab: { flex: 1, paddingVertical: 12, borderRadius: 12, alignItems: 'center' },
  tabActive: { backgroundColor: '#8a1538' },
  tabText: { fontWeight: '900', textTransform: 'capitalize' },
  body: { flex: 1, paddingHorizontal: 10 },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingVertical: 8 },
  filterChip: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7, minHeight: 36 },
  filterChipActive: { backgroundColor: '#8a1538', borderColor: '#8a1538' },
  listContent: { paddingBottom: 132 },
  emptyList: { flexGrow: 1, justifyContent: 'center' },
  emptyState: { alignItems: 'center', paddingHorizontal: 32 },
  emptyTitle: { fontSize: 22, fontWeight: '900' },
  emptyText: { marginTop: 6, fontSize: 15 },
  card: { borderWidth: 1, borderRadius: 14, padding: 10, marginBottom: 8 },
  compactCard: { padding: 7, marginBottom: 6 },
  pinnedCard: { borderLeftWidth: 5, borderLeftColor: '#8a1538' },
  doneCard: { opacity: 0.72 },
  cardTopRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8, alignItems: 'flex-start' },
  badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, flex: 1 },
  badge: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 },
  badgeText: { fontWeight: '900', fontSize: 10, textTransform: 'uppercase' },
  cardActions: { flexDirection: 'row', gap: 4, alignItems: 'center' },
  actionButton: { paddingVertical: 6, paddingHorizontal: 6, minHeight: 34, justifyContent: 'center' },
  iconActionButton: { paddingVertical: 5, paddingHorizontal: 7, minHeight: 34, minWidth: 34, justifyContent: 'center', alignItems: 'center' },
  taskText: { fontSize: 16, fontWeight: '800', lineHeight: 21, marginTop: 8 },
  compactTaskText: { fontSize: 14, lineHeight: 18, marginTop: 5 },
  doneText: { textDecorationLine: 'line-through' },
  metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 6 },
  metaText: { fontSize: 12, fontWeight: '700' },
  statusRow: { flexDirection: 'row', gap: 5, marginTop: 8 },
  statusButton: { flex: 1, borderWidth: 1, borderRadius: 8, minHeight: 34, alignItems: 'center', justifyContent: 'center' },
  compactStatusButton: { minHeight: 30 },
  cardUtilityRow: { flexDirection: 'row', gap: 6, marginTop: 7 },
  utilityButton: { flex: 1, borderWidth: 1, borderRadius: 8, minHeight: 32, alignItems: 'center', justifyContent: 'center' },
  bottomActionColumn: { position: 'absolute', left: 12, right: 12, bottom: 12, gap: 8 },
  bottomActionRow: { flexDirection: 'row', gap: 8 },
  sameLocationButton: { borderWidth: 1, borderRadius: 14, padding: 11, alignItems: 'center', minHeight: 44, justifyContent: 'center' },
  bottomAddButton: { flex: 1, backgroundColor: '#8a1538', borderRadius: 14, padding: 14, alignItems: 'center', minHeight: 52, justifyContent: 'center' },
  clearDoneButton: { flex: 1, borderWidth: 1, borderRadius: 14, padding: 14, alignItems: 'center', minHeight: 52, justifyContent: 'center' },
  modalSafe: { flex: 1 },
  modalHeader: { height: 60, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12 },
  modalHeaderButton: { minWidth: 78, minHeight: 44, justifyContent: 'center', alignItems: 'center' },
  modalSaveButton: { backgroundColor: '#8a1538', borderRadius: 12, paddingHorizontal: 12 },
  modalSaveText: { color: '#ffffff', fontWeight: '900', fontSize: 16 },
  modalTitle: { fontSize: 18, fontWeight: '900' },
  formContent: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 180 },
  label: { fontSize: 14, fontWeight: '900', marginBottom: 6, marginTop: 10 },
  fieldHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginTop: 10, marginBottom: 6 },
  fieldHeaderLabel: { marginTop: 0, marginBottom: 0 },
  shortcutTriggerButton: { borderWidth: 1, borderRadius: 999, minHeight: 38, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  shortcutTriggerText: { fontSize: 13, fontWeight: '900' },
  fieldHint: { fontSize: 12, fontWeight: '700', marginTop: -2, marginBottom: 6 },

  shortcutOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.52)', alignItems: 'center', justifyContent: 'center', padding: 18 },
  shortcutWheel: { width: '92%', maxWidth: 380, borderWidth: 1, borderRadius: 24, padding: 16, alignItems: 'center' },
  shortcutTitle: { fontSize: 18, fontWeight: '900', marginBottom: 12 },
  radialMenuStage: { width: 272, height: 272, position: 'relative' },
  shortcutOptionButton: { position: 'absolute', borderWidth: 1, borderRadius: 999, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8 },
  shortcutOptionText: { fontSize: 15, fontWeight: '900', textAlign: 'center' },
  shortcutCenterButton: { position: 'absolute', left: 94, top: 104, width: 84, height: 64, borderWidth: 1, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  shortcutDismissText: { fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  shortcutHintBottom: { fontSize: 12, fontWeight: '700', marginTop: 10 },
  helpText: { fontSize: 14, lineHeight: 20 },
  mainInput: { minHeight: 112, maxHeight: 180, borderWidth: 1, borderRadius: 16, padding: 12, fontSize: 18, lineHeight: 24 },
  input: { borderWidth: 1, borderRadius: 14, padding: 13, minHeight: 48, fontSize: 16 },
  multiLineInput: { minHeight: 82, textAlignVertical: 'top' },
  segmentedRow: { flexDirection: 'row', gap: 8 },
  typeChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  typeChip: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 8, minHeight: 38 },
  typeChipActive: { backgroundColor: '#8a1538', borderColor: '#8a1538' },
  segment: { flex: 1, borderWidth: 1, borderRadius: 14, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  handoverContent: { paddingVertical: 16, paddingBottom: 42 },
  sectionTitle: { fontSize: 22, fontWeight: '900', marginBottom: 8 },
  sectionSubtitle: { fontSize: 17, fontWeight: '900', marginBottom: 8 },
  handoverBox: { borderWidth: 1, borderRadius: 16, padding: 14, marginTop: 14 },
  handoverText: { fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }), fontSize: 15, lineHeight: 22 },
  undoBar: { position: 'absolute', left: 12, right: 12, bottom: 74, borderWidth: 1, borderRadius: 14, paddingVertical: 10, paddingLeft: 14, paddingRight: 8, minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 10, shadowColor: '#000', shadowOpacity: 0.24, shadowRadius: 10, elevation: 6 },
  undoText: { flex: 1, fontSize: 14, fontWeight: '800' },
  undoButton: { backgroundColor: '#8a1538', borderRadius: 10, paddingHorizontal: 14, minHeight: 36, justifyContent: 'center' },
  undoButtonText: { color: '#ffffff', fontWeight: '900' },
  undoDismiss: { minWidth: 34, minHeight: 36, alignItems: 'center', justifyContent: 'center' },
  undoDismissText: { fontSize: 24, fontWeight: '700' },
  warningText: { fontSize: 13, lineHeight: 18, marginTop: 12, fontWeight: '700' },
  waitingText: { fontSize: 13, fontWeight: '800', marginTop: 5 },
  reviewLine: { fontSize: 14, lineHeight: 21, marginTop: 4, fontWeight: '700' },
  shiftCard: { borderWidth: 1, borderRadius: 14, padding: 10, marginTop: 8 },
  horizontalControls: { flexGrow: 0 },
  horizontalControlContent: { gap: 6, paddingVertical: 7, paddingRight: 18 },
  groupHeader: { fontSize: 15, fontWeight: '900', paddingVertical: 8, borderBottomWidth: 1, marginBottom: 6 },
  settingsContent: { paddingVertical: 16, paddingBottom: 42 },
  settingsCard: { borderWidth: 1, borderRadius: 16, padding: 14, marginTop: 12 },
  settingsRowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  settingsRowText: { flex: 1 },
  toggleButton: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 16, minHeight: 42, alignItems: 'center', justifyContent: 'center' },
  toggleButtonActive: { backgroundColor: '#8a1538', borderColor: '#8a1538' },
  dangerButton: { backgroundColor: '#991b1b', padding: 16, borderRadius: 14, alignItems: 'center', marginTop: 18, minHeight: 52, justifyContent: 'center' },
  dangerButtonText: { color: '#fee2e2', fontWeight: '900', fontSize: 16 },
});